name: prometheus-node-exporter
summary: Prometheus Node Exporter
description: |
  Prometheus exporter for hardware and OS metrics exposed by *NIX kernels, written in Go with pluggable metric collectors.

adopt-info: prometheus-node-exporter

grade: stable
confinement: classic

base: core20

apps:
  prometheus-node-exporter:
    daemon: simple
    environment:
      PATH: /snap/bin
    command: wrappers/node_exporter

parts:
  prometheus-node-exporter:
    source: https://github.com/prometheus/node_exporter.git
    plugin: go
    go-channel: 1.14/stable
    override-build: |
      snapcraftctl build
      snapcraftctl set-version `cat VERSION`
  wrappers:
    source: src/
    plugin: dump
